const puppeteer = require("puppeteer-core");
const fs = require("fs");
const dir = "C:/Users/imadj/Desktop/naturesdates/verify-shots";
fs.mkdirSync(dir, { recursive: true });
(async () => {
  const b = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new", args: ["--no-sandbox","--disable-gpu","--hide-scrollbars"] });
  const p = await b.newPage();
  await p.setViewport({ width: 1440, height: 900 });
  await p.goto("http://localhost:3000/", { waitUntil: "networkidle0", timeout: 60000 });
  await new Promise(r=>setTimeout(r,800));
  const yTop = await p.evaluate(()=>{const m=document.querySelector(".home-categories");const r=m.getBoundingClientRect();return Math.round(r.top+window.scrollY+20);});
  await p.evaluate((yy)=>window.scrollTo(0,yy), yTop);
  await new Promise(r=>setTimeout(r,300));
  await p.screenshot({ path: `${dir}/cat-top-1440.png` });
  const yBot = await p.evaluate(()=>{const m=document.querySelector(".home-categories");const r=m.getBoundingClientRect();return Math.round(r.top+window.scrollY + m.scrollHeight - window.innerHeight + 20);});
  await p.evaluate((yy)=>window.scrollTo(0,Math.max(0,yy)), yBot);
  await new Promise(r=>setTimeout(r,300));
  await p.screenshot({ path: `${dir}/cat-bot-1440.png` });
  await b.close();
  console.log("DONE");
})().catch(e=>{console.error(e);process.exit(1);});
